### ISSUE TITLE
Feature request: turn off the check for warnings via an environment variable

### ISSUE THREAD

**Issue by perlpunk** [karenetheridge/Test-Warnings#12]
Background: There was an update of Mojolicious 9.34 which deprecated a method and added the new replacement method in the same release, so we got deprecation warnings that made all our tests fail (the deprecated method is used all over our code). So we have the pressure to update our code immediately.
It would be good if we could turn off the check for warnings easily without changing every test file in such cases, ideally with an environment variable.
I've seen #8 , which also looks like a good idea, but we would still have to update all our tests. But at least adding that `-pattern => qr/.../` would work with a simple oneliner replacement call.

**Comment by kraih** [comment]
This does seem like a good idea.
